// Generated by https://quicktype.io

export interface LoginResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    estadoVacunas: string;
    rol:           string;
    estado:        boolean;
    google:        boolean;
    nombre:        string;
    apellido:      string;
    cedula:        number;
    correo:        string;
    uid:           string;
}
