// Generated by https://quicktype.io

export interface UsersResponse {
    total:    number;
    usuarios: Usuario[];
}

export interface Usuario {
    estadoVacunas: string;
    rol:           string;
    estado:        boolean;
    google:        boolean;
    nombre:        string;
    apellido:      string;
    cedula:        number;
    correo:        string;
    uid:           string;
}
